Repository IBM/varnish-operator, pull requests merged in 2021-03, with the labels that each got.

#17 Make grafana dashboard name unique and create title override
  api/v1alpha1/varnishcluster_types.go
  config/crd/bases/caching.ibm.com_varnishclusters.yaml
  docs/operator-configuration.md
  docs/varnish-cluster-configuration.md
  pkg/names/names.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard_template.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard_test.go
  tests/garbage_collection_test.go
  varnish-operator/crds/varnishcluster.yaml
Labels: enhancement

#20 Fix pulling in metrics from foreign varnishclusters in the built-in grafana dashboard.
  config/samples/varnishcluster.yaml
  helm-releases/index.yaml
  pkg/varnishcluster/controller/varnishcluster_controller.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard_template.go
  pkg/varnishcluster/controller/varnishcluster_servicemonitor.go
  varnish-operator/Chart.yaml
  varnish-operator/crds/varnishcluster.yaml
  varnish-operator/templates/clusterrole.yaml
  varnish-operator/values.yaml
Labels: enhancement

#21 Reset pervious operator version
  api/v1alpha1/zz_generated.deepcopy.go
  helm-releases/index.yaml
Labels: bug

#22 Fix grafana dashboard title documentation
  docs/operator-configuration.md
  docs/varnish-cluster-configuration.md
Labels: documentation

#26 Add service name + namespace to grafana dashboard metrics
  config/samples/varnishcluster.yaml
  docs/varnish-cluster-configuration.md
  varnish-operator/templates/grafana-dashboard.yaml
Labels: enhancement

#25 Make management port available outside of the pod
  .github/workflows/containers.yml
  docs/varnish-cluster.md
  go.mod
  go.sum
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard_template.go
  pkg/varnishcluster/controller/varnishcluster_grafana_dashboard_test.go
  pkg/varnishcluster/controller/varnishcluster_statefulset_test.go
  pkg/varnishcluster/controller/varnishcluster_varnish_args.go
  pkg/varnishcluster/controller/varnishcluster_varnish_args_test.go
Labels: enhancement
